server:
  port: 8087
spring:
  application:
    name: keycloak-rest-apis
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}
          jwk-set-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/certs
        opaquetoken:
          client-id:
keycloak:
  auth-server-url: http://localhost:8088
  realm: sample
  resource: spring-boot-app
  credentials:
    secret: mpJEaCVLwEN4S3EwyOMZ2IZW09XS0PCY