server:
  port: 8001
spring:
  application:
    name: keycloak-rest-apis
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}
          jwk-set-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/certs
keycloak:
  auth-server-url: http://localhost:8000
  realm: sample
  resource: spring-boot-api
  credentials:
    secret: ${KEYCLOAK_CREDENTIALS_SECRET}